const colors = {
  light: {
    text: "#1a1a1a",
    tint: "#e85d04",
    background: "#f8f7f4",
    foreground: "#1a1a1a",
    card: "#ffffff",
    cardForeground: "#1a1a1a",
    primary: "#e85d04",
    primaryForeground: "#ffffff",
    secondary: "#f0ede8",
    secondaryForeground: "#1a1a1a",
    muted: "#f0ede8",
    mutedForeground: "#8a8278",
    accent: "#ff7b35",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e8e4de",
    input: "#f0ede8",
  },
  dark: {
    text: "#f2ede8",
    tint: "#e85d04",
    background: "#0e0c0a",
    foreground: "#f2ede8",
    card: "#1a1714",
    cardForeground: "#f2ede8",
    primary: "#e85d04",
    primaryForeground: "#ffffff",
    secondary: "#242018",
    secondaryForeground: "#f2ede8",
    muted: "#242018",
    mutedForeground: "#7a7468",
    accent: "#ff7b35",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#2e2a24",
    input: "#242018",
  },
  radius: 12,
};

export default colors;
